# Generated by Django 2.1.3 on 2019-10-22 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'invalid': 'Неправильно называние товара'}, max_length=50, unique_for_date='published', validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20000000, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published'), ('title', 'price')},
        ),
    ]
