# Generated by Django 2.1.3 on 2019-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20191022_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('None', 'Выберите разряд публикуемого обьявленя'), ('Куплю', 'Куплю'), ('Продам', 'Продам'), ('Обменяю', 'Обменяю')], default=True, max_length=10),
        ),
    ]
