# Generated by Django 2.1.3 on 2019-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20191023_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[('None', 'Выберите разряд публикуемого обьявленя'), ('Куплю', 'Куплю'), ('Продам', 'Продам'), ('Обменяю', 'Обменяю')], default=True, max_length=10, verbose_name='Сортировка'),
        ),
    ]
